version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD: cs348user
      MYSQL_DATABASE: cs348
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      DBHOST: mysql
      DB: cs348
      USER: webapp
      PASSWORD: cs348user