# Generated by Django 4.1.2 on 2022-10-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_in_tags',
            fields=[
                ('tag_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('task_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('uid', 'tag_name', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('F', 'Finished'), ('IP', 'In Progress')], max_length=2)),
                ('task_created', models.DateField()),
                ('task_started', models.DateField()),
                ('task_due', models.DateField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'unique_together': {('uid', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('uid', 'tag_name')},
            },
        ),
    ]
