# Generated by Django 4.1.2 on 2022-10-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_started',
            field=models.DateField(null=True),
        ),
    ]
