# Generated by Django 4.1.2 on 2022-10-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('Fi', 'Finished'), ('IP', 'In Progress')], max_length=2),
        ),
    ]
