version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD: cs348user
      MYSQL_DATABASE: cs348
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  test:
    build: ../
    command: npm test
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      DBHOST: mysql
      DB: cs348
      USER: webapp
      PASSWORD: cs348user